// Code generated by hl7 dynamic generator. DO NOT EDIT.
package hl7


// HierarchicalData represents the HL7 data type definition.
type HierarchicalData struct {
	NamespaceId IS `json:"NamespaceId" hl7:"table:0300"`
	UniversalId string `json:"UniversalId" hl7:""`
	UniversalIdType ID `json:"UniversalIdType" hl7:"table:0301"`
}

// TimeStamp represents the HL7 data type definition.
type TimeStamp struct {
	TimeStampField1 string `json:"TimeStampField1" hl7:"mandatory,length:26"`
}

// MessageType represents the HL7 data type definition.
type MessageType struct {
	MessageType ID `json:"MessageType" hl7:"table:0076"`
	TriggerEvent ID `json:"TriggerEvent" hl7:"table:0003"`
	MessageStructure ID `json:"MessageStructure" hl7:"table:0354"`
}

// MSH represents the HL7 data type definition.
type MSH struct {
	Hl7SegmentName string `json:"Hl7SegmentName" hl7:"length:3,table:0076"`
	SendingApplication HierarchicalData `json:"SendingApplication" hl7:"length:180"`
	SendingFacility HierarchicalData `json:"SendingFacility" hl7:"length:180"`
	ReceivingApplication HierarchicalData `json:"ReceivingApplication" hl7:"length:180"`
	ReceivingFacility HierarchicalData `json:"ReceivingFacility" hl7:"length:180"`
	DateOrTimeOfMessage TimeStamp `json:"DateOrTimeOfMessage" hl7:"length:4"`
	Security string `json:"Security" hl7:"length:40"`
	MessageType MessageType `json:"MessageType" hl7:"mandatory,length:7"`
	MessageControlId string `json:"MessageControlId" hl7:"mandatory,length:20"`
	ProcessingId ProcessingType `json:"ProcessingId" hl7:"mandatory,length:3"`
	VersionId VersionId `json:"VersionId" hl7:"mandatory,length:60"`
}

// HL7 represents the HL7 data type definition.
type HL7 struct {
	Msh MSH `json:"Msh" hl7:"mandatory"`
}

// ID represents the HL7 data type definition.
type ID struct {
	IDField1 string `json:"IDField1" hl7:"mandatory,length:26"`
}

// ProcessingType represents the HL7 data type definition.
type ProcessingType struct {
	ProcessingId ID `json:"ProcessingId" hl7:"table:0103"`
	ProcessingMode ID `json:"ProcessingMode" hl7:"table:0207"`
}

// CodedElement represents the HL7 data type definition.
type CodedElement struct {
	Identifier string `json:"Identifier" hl7:""`
	Text string `json:"Text" hl7:""`
	NameOfCodingSystem string `json:"NameOfCodingSystem" hl7:""`
	AlternateComponents string `json:"AlternateComponents" hl7:""`
	AlternateText string `json:"AlternateText" hl7:""`
	NameOfAlternateCodingSystem string `json:"NameOfAlternateCodingSystem" hl7:""`
}

// VersionId represents the HL7 data type definition.
type VersionId struct {
	VersionId ID `json:"VersionId" hl7:"table:0104"`
	InternationalizationCode CodedElement `json:"InternationalizationCode" hl7:""`
	InternationalVersionId CodedElement `json:"InternationalVersionId" hl7:""`
}

// IS represents the HL7 data type definition.
type IS struct {
	ISField1 string `json:"ISField1" hl7:"mandatory,length:26"`
}

